### ISSUE TITLE
Theano scan error while training model

### ISSUE THREAD

**Issue by chaitanyamalaviya** [tuzhaopeng/NMT-Coverage#3]
Hi, 

I was trying to train a model using the following command on a custom dataset:
`python train.py --state german-data.py `
I tried this with theano version 0.8.2 and 0.9 as well.
I faced the following error:
```
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    main()
  File "train.py", line 81, in main
    enc_dec.build()
  File "/projects/tir1/users/cmalaviy/NMT-Coverage/experiments/nmt/encdec.py", line 1864, in build
    c=self.sampling_c)
  File "/projects/tir1/users/cmalaviy/NMT-Coverage/experiments/nmt/encdec.py", line 1725, in build_sampler
    name="{}_sampler_scan".format(self.prefix))
  File "/projects/tir1/users/cmalaviy/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan.py", line 1071, in scan
    scan_outs = local_op(*scan_inputs)
  File "/projects/tir1/users/cmalaviy/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/projects/tir1/users/cmalaviy/anaconda2/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 578, in make_node
    inner_sitsot_out.type.ndim))
ValueError: When compiling the inner function of scan (the function called by scan in each of its iterations) the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 4) has 4 dimension(s), while the corresponding variable in the result of the inner function of scan (`fn`) has 1 dimension(s) (it should be one less than the initial state). For example, if the inner function of scan returns a vector of size d and scan uses the values of the previous time-step, then the initial state in scan should be a matrix of shape (1, d). The first dimension of this matrix corresponds to the number of previous time-steps that scan uses in each of its iterations. In order to solve this issue if the two varialbe currently have the same dimensionality, you can increase the dimensionality of the variable in the initial state of scan by using dimshuffle or shape_padleft. 
```
Would appreciate any help.

Thanks!

**Comment by tuzhaopeng** [comment]
Have you modified the code? It seems that the error is not caused by the theano version, but possibly by a wrong dimensionality of the argument number 4 in a scan function.

**Comment by chaitanyamalaviya** [comment]
I wasn't able to run the code from this repo. Instead, I tried training the coverage model from this repo: https://github.com/tuzhaopeng/NMT with different datasets and I noticed that the model keeps diverging.

**Comment by tuzhaopeng** [comment]
Other users have also reported the diverging problem of coverage model using https://github.com/tuzhaopeng/NMT. 

Since the code is a little out of date, I have moved to a new in-house implementation of RNNSearch, in which the coverage model works well on both Chinese-English and German-English translation tasks. I will clean the code and try to upload it as soon as possible.

Sorry for the inconvenience.

**Comment by tuzhaopeng** [comment]
Please try our newly updated code via https://github.com/tuzhaopeng/NMT , which is more clean and powerful.
